import test from 'node:test';
import assert from 'node:assert/strict';
import {authorize} from '../functions/_lib/http.js';
import {onRequestGet as rates} from '../functions/api/rates.js';
import {onRequestGet as naver} from '../functions/api/naver.js';
import {onRequest as sync} from '../functions/api/sync.js';
import {onRequest as middleware} from '../functions/_middleware.js';
const token='a'.repeat(64),env={API_ACCESS_TOKEN:token,NAVER_CLIENT_ID:'test-id',NAVER_CLIENT_SECRET:'test-secret'};
const req=(path,auth=token)=>new Request('https://trip.example'+path,{headers:auth?{Authorization:'Bearer '+auth}:{}});
test('private API fails closed without configuration',async()=>assert.equal((await authorize(req('/api/naver'),{})).status,503));
test('private API rejects absent or wrong token',async()=>{assert.equal((await authorize(req('/api/naver',''),env)).status,401);assert.equal((await authorize(req('/api/naver','wrong'),env)).status,401);assert.equal(await authorize(req('/api/naver'),env),null);});
test('private API rejects cross-origin requests',async()=>{const r=new Request('https://trip.example/api/naver',{headers:{Authorization:'Bearer '+token,Origin:'https://evil.example'}});assert.equal((await authorize(r,env)).status,403);});
test('Naver rejects long search input before an upstream call',async()=>assert.equal((await naver({request:req('/api/naver?q='+'q'.repeat(101)),env})).status,400));
test('Naver exposes normalized metadata, never the credentials',async()=>{const original=globalThis.fetch;let target;globalThis.fetch=async(url,opts)=>{target=String(url);assert.equal(opts.headers['X-NCP-APIGW-API-KEY'],'test-secret');return Response.json({items:[{title:'<b>경복궁</b>',roadAddress:'서울',mapx:'1269784000',mapy:'375665000'}]});};try{const r=await naver({request:req('/api/naver?q=test'),env}),body=await r.json();assert.equal(r.status,200);assert.equal(body.items[0].name,'경복궁');assert.equal(JSON.stringify(body).includes('test-secret'),false);assert.match(target,/display=5/);assert.match(target,/^https:\/\/naverapihub\.apigw\.ntruss\.com\/search\/v1\/local\?/);assert.equal(r.headers.get('Cache-Control'),'no-store');}finally{globalThis.fetch=original;}});
test('Naver upstream failures return useful errors without a success payload',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response('',{status:429});try{const r=await naver({request:req('/api/naver?q=test'),env});assert.equal(r.status,502);assert.ok((await r.json()).error);}finally{globalThis.fetch=old;}});
test('exchange rate uses the fixed USD/KRW upstream and validates the payload',async()=>{const old=globalThis.fetch;globalThis.fetch=async(url)=>{assert.equal(String(url),'https://api.frankfurter.dev/v2/rates?base=USD&quotes=KRW');return Response.json([{base:'USD',quote:'KRW',rate:1400,date:'2026-01-01'}]);};try{const r=await rates({}),body=await r.json();assert.equal(r.status,200);assert.equal(body.rate,1400);}finally{globalThis.fetch=old;}});
test('invalid rate provider responses cannot overwrite a saved reference',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json([{base:'EUR',quote:'KRW',rate:1400,date:'2026-01-01'}]);try{assert.equal((await rates({})).status,502);}finally{globalThis.fetch=old;}});
test('sync stub never claims that data was uploaded',async()=>{const r=await sync({request:req('/api/sync'),env});assert.equal(r.status,501);assert.equal((await r.json()).code,'SYNC_NOT_IMPLEMENTED');});
test('Function middleware sets no-store even when the handler does not',async()=>{const r=await middleware({next:async()=>Response.json({ok:true})});assert.equal(r.headers.get('Cache-Control'),'no-store');assert.ok(r.headers.get('Content-Security-Policy').includes("default-src 'none'"));});
