import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {CHECKLIST,checklistProgress,checklistMetaKey,restorableChecklist,validateChecklistRecord} from '../public/src/checklist.js';
import {LOCAL_IDEAS} from '../public/src/locality.js';
import {cleanPlace,safeURL,mapLinks} from '../public/src/domain.js';
import {cleanStay,mergeStayAddress} from '../public/src/stay.js';
import {STAY_SEED} from '../public/src/stay-seed.js';
import {validEnvelope,unseal} from '../public/src/crypto.js';
import {validateSnapshot} from '../public/src/db.js';
test('checklist has twelve stable unique IDs and counts only true confirmations',()=>{assert.equal(CHECKLIST.length,12);assert.equal(new Set(CHECKLIST.map(x=>x.id)).size,12);assert.deepEqual(checklistProgress({documents:true,maps:true,offline:'true'}),{done:2,total:12});});
test('device confirmations cannot be restored as travel-wide completions',()=>{for(const x of CHECKLIST)assert.equal(restorableChecklist(checklistMetaKey(x.id)),!x.device);assert.throws(()=>checklistMetaKey('unknown'));});
test('invalid checklist metadata in backups is rejected',()=>{assert.throws(()=>validateChecklistRecord('check:maps','true'));assert.throws(()=>validateSnapshot({schema:1,places:[],photos:[],meta:[{id:'check:offline',value:'yes'}]}));});
test('six local ideas have valid sources and can be saved in the existing model',()=>{assert.equal(LOCAL_IDEAS.length,6);for(const p of LOCAL_IDEAS){assert.ok(safeURL(p.sourceURL));assert.ok(cleanPlace({...p,links:[p.sourceURL]}).name);assert.equal(p.lat,undefined);assert.equal(p.lng,undefined);}});
test('stay address merge preserves PIN, room, Wi-Fi and personal notes',()=>{const old=cleanStay({name:'My booking',addressKo:'기존 주소',pin:'1234#',room:'A',wifi:'mywifi',note:'Keep me'});const merged=mergeStayAddress(old,{addressKo:'새 주소',addressEn:'New address',lat:37.5,lng:127.0});assert.equal(merged.pin,'1234#');assert.equal(merged.name,'My booking');assert.equal(merged.note,'Keep me');assert.equal(merged.lat,37.5);});
test('legacy stays without coordinates remain readable; partial coordinates fail',()=>{assert.equal(cleanStay({addressKo:'서울'}).lat,null);assert.throws(()=>cleanStay({addressKo:'서울',lat:37.5}));assert.throws(()=>cleanStay({addressKo:'서울',lat:1,lng:2}));});
test('stay direction links cannot contain an entry PIN',()=>{const links=mapLinks({name:'Stay',korean:'숙소',address:'서울',lat:37.5,lng:127,pin:'PRIVATE-CODE'});assert.ok(links.transit.startsWith('nmap://'));assert.ok(!JSON.stringify(links).includes('PRIVATE-CODE'));});
test('supplied seed is authenticated ciphertext, not plaintext address metadata',()=>{assert.ok(validEnvelope(STAY_SEED.envelope,'stay'));assert.equal(STAY_SEED.addressKo,undefined);assert.equal(STAY_SEED.passphrase,undefined);});
test('owner-only setup decrypts to the supplied exact source when local source is present',async t=>{let source,owner;try{source=JSON.parse(await readFile(new URL('../private/stay-source.json',import.meta.url),'utf8'));owner=await readFile(new URL('../private/OWNER_SETUP.md',import.meta.url),'utf8');}catch(err){if(err.code==='ENOENT'){t.skip('Private setup intentionally absent from this checkout.');return;}throw err;}const key=owner.match(/^Seoul-[A-Za-z0-9_-]+$/m)?.[0];assert.ok(key);const v=await unseal(STAY_SEED.envelope,key,'stay');assert.deepEqual(v,source);assert.equal(v.pin,'');assert.equal(v.room,'');});
test('app contains currency swap and fixed zones, not select menus',async()=>{const app=await readFile(new URL('../public/src/app.js',import.meta.url),'utf8');assert.ok(app.includes("case 'swap-currency'"));assert.ok(app.includes("case 'zone-source'"));assert.ok(!app.includes('<select'));assert.ok(!app.includes('${select('));});
